<?php

namespace App\Command;

use App\Project\StateResolver;
use App\Project\Task;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Finder\SplFileInfo;

class ProjectCommand extends Command
{
    protected static $defaultName = 'app:project';

    private $projectDir;
    private $stateResolver;

    public function __construct(string $projectDir, StateResolver $stateResolver, string $name = null)
    {
        parent::__construct($name);
        $this->projectDir = $projectDir;
        $this->stateResolver = $stateResolver;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $finder = new Finder();
        /** @var SplFileInfo[] $files */
        $files = $finder->files()->in($this->projectDir);

        foreach ($files as $file) {
            $task = new Task($file);
            $output->writeln(
                sprintf(
                    '%s (%s)',
                    $task->getTitle(),
                    $this->stateResolver->resolveState($task)
                )
            );
        }

        return 0;
    }
}
