<?php

namespace App\Command;

use App\Project\Project;
use App\Project\StateResolver;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ProjectCommand extends Command
{
    protected static $defaultName = 'app:project';

    private $project;
    private $stateResolver;

    public function __construct(Project $project, StateResolver $stateResolver, string $name = null)
    {
        parent::__construct($name);
        $this->project = $project;
        $this->stateResolver = $stateResolver;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $tasks = $this->project->getTasks();

        foreach ($tasks as $task) {
            $output->writeln($task->getTitleWithState());
        }

        return 0;
    }
}
