<?php

namespace App\Command;

use App\Project\ProjectFactory;
use App\Project\Task;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class TasksCommand extends Command
{
    protected static $defaultName = 'app:tasks';

    private $projectFactory;

    public function __construct(ProjectFactory $projectFactory, string $name = null)
    {
        parent::__construct($name);
        $this->projectFactory = $projectFactory;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->addOption('repo', 'r', InputOption::VALUE_REQUIRED, 'path to the repository', '.');
        $this->addOption('tasks', 't', InputOption::VALUE_REQUIRED, 'path to tasks (relative to repo path)', 'tasks');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);

        $project = $this->projectFactory->createProject($input->getOption('repo'), $input->getOption('tasks'));

        $lanes = $project->getLanes();

        foreach ($lanes as $lane) {
            $io->section($lane->getName());
            $io->listing(
                array_map(
                    static function (Task $task) {
                        return $task->getTitleWithState();
                    },
                    $lane->getTasks()
                )
            );
        }

        return 0;
    }
}
