parameters:
    app.projects:
        kodo:
            name: 'KoDo'
            repo_path: '%kernel.project_dir%'
            tasks_dir: 'tasks'

        simple_sample:
            name: 'Simple Sample'
            repo_path: '%kernel.project_dir%/example_projects/simple_sample'
            tasks_dir: 'project'

        does_not_exist:
            name: 'This does not exist'
            repo_path: '/dev/null'
            tasks_dir: 'nothing'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Project\ProjectRepository:
        $configs: '%app.projects%'
